# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0002_books_book_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='Book_cover',
            new_name='book_cover',
        ),
    ]
