# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 23:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_auto_20171113_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
